import { DEFAULT_AGENT_TIMEOUT_SECONDS, type DiscoveredConfig, MAX_AGENT_TIMEOUT_SECONDS } from "../config/discover.js";
import { AgentsFileParseError, AgentsFileReadError, loadAgentsFile, locateAgentsFile } from "./agentsFile.js";

/**
 * Three-tier BYO agent command resolution, shared by `triage --run` and
 * `init --run`: an explicit `--agent-command` CLI flag or
 * `GATEKEEPER_AGENT_COMMAND` env var wins outright, then `.gatekeeper.yml`'s
 * `agent.command`, then -- as a last-resort convenience fallback, never
 * required -- `governance/agents.yaml`'s selection for the given role tier
 * (see src/agent/agentsFile.ts; generated by `gatekeeper init-control`'s
 * detection pass, src/agent/detect.ts + src/agent/assign.ts). Each caller
 * reports which tier resolved the command it ends up running, so a user
 * looking at `--run` output can tell where the command came from without
 * having to inspect three separate files.
 */

export type AgentCommandSource = "cli" | "env" | "config" | "agents.yaml";

export interface ResolvedAgentCommand {
	command: string;
	timeoutSeconds: number;
	source: AgentCommandSource;
	/** Human-readable one-liner for --run's "using agent from ..." output line. */
	description: string;
}

export interface ResolveAgentCommandInput {
	/** `--agent-command` CLI flag value, if given. */
	cliCommand?: string;
	/** `--agent-timeout` CLI flag value (seconds), if given. Only consulted when cliCommand is also given. */
	cliTimeoutSeconds?: number;
	/** Defaults to process.env. Only GATEKEEPER_AGENT_COMMAND / GATEKEEPER_AGENT_TIMEOUT_SECONDS are consulted. */
	env?: NodeJS.ProcessEnv;
	discovered: DiscoveredConfig | null;
	/**
	 * The already-resolved registry directory (see resolveRegistryOption) --
	 * used to locate a sibling governance/agents.yaml. `undefined` when the
	 * caller has no registry resolvable at all (e.g. `init` without a
	 * discoverable `.gatekeeper.yml`) -- tier 3 is simply unavailable then,
	 * same as an agents.yaml that doesn't exist.
	 */
	registryPath: string | undefined;
	/** Which roles-policy.yaml tier's agents.yaml assignment to fall back to. */
	role: "deep-reasoner" | "coder";
}

/**
 * Thrown when `--agent-timeout` or `GATEKEEPER_AGENT_TIMEOUT_SECONDS` names a
 * value above MAX_AGENT_TIMEOUT_SECONDS. Commander already rejects an
 * out-of-range `--agent-timeout` before it ever reaches this module (see
 * cli.ts's/init.ts's bounded validator) -- this class exists primarily for
 * the env-var path, which has no commander validator to intercept it, plus
 * as defense-in-depth for any caller that constructs
 * ResolveAgentCommandInput directly. Callers map this to the same exit-2
 * usage-error posture as every other out-of-range CLI input.
 */
export class AgentTimeoutRangeError extends Error {
	readonly source: "cli" | "env";
	readonly value: number;

	constructor(source: "cli" | "env", value: number) {
		super(
			`${source === "cli" ? "--agent-timeout" : "GATEKEEPER_AGENT_TIMEOUT_SECONDS"} (${value}) exceeds the maximum of ${MAX_AGENT_TIMEOUT_SECONDS} seconds`,
		);
		this.name = "AgentTimeoutRangeError";
		this.source = source;
		this.value = value;
	}
}

/** Rejects (throws AgentTimeoutRangeError) a positive timeout above the shared cap; passes any other value through unchanged (callers apply their own default/NaN handling). */
function rejectIfOverMax(value: number, source: "cli" | "env"): number {
	if (value > MAX_AGENT_TIMEOUT_SECONDS) {
		throw new AgentTimeoutRangeError(source, value);
	}
	return value;
}

/**
 * Resolves the BYO agent command through the three-tier chain described
 * above. Returns `undefined` when none of the three tiers has anything
 * configured -- callers fall back to their existing missingAgentMessage
 * error path unchanged. A governance/agents.yaml that exists but fails to
 * read/parse still degrades tier 3 to "contributes nothing" (this fallback
 * tier is a convenience, not a hard dependency, and a stale/broken
 * agents.yaml must never block a command that already has -- or is about to
 * fail loud on -- tiers 1/2) -- but the failure is no longer silent: a
 * warning naming the file and the reason is written to stderr first, so a
 * genuinely damaged agents.yaml is never indistinguishable from "nothing
 * configured" in the eventual missingAgentMessage output.
 *
 * @throws AgentTimeoutRangeError when `cliTimeoutSeconds` or
 *   `GATEKEEPER_AGENT_TIMEOUT_SECONDS` exceeds MAX_AGENT_TIMEOUT_SECONDS.
 */
export async function resolveAgentCommand(input: ResolveAgentCommandInput): Promise<ResolvedAgentCommand | undefined> {
	if (input.cliCommand) {
		const timeoutSeconds =
			input.cliTimeoutSeconds !== undefined
				? rejectIfOverMax(input.cliTimeoutSeconds, "cli")
				: DEFAULT_AGENT_TIMEOUT_SECONDS;
		return {
			command: input.cliCommand,
			timeoutSeconds,
			source: "cli",
			description: "using agent from --agent-command",
		};
	}

	const env = input.env ?? process.env;
	if (env.GATEKEEPER_AGENT_COMMAND) {
		const parsedTimeout = env.GATEKEEPER_AGENT_TIMEOUT_SECONDS
			? Number(env.GATEKEEPER_AGENT_TIMEOUT_SECONDS)
			: Number.NaN;
		const timeoutSeconds =
			Number.isInteger(parsedTimeout) && parsedTimeout > 0
				? rejectIfOverMax(parsedTimeout, "env")
				: DEFAULT_AGENT_TIMEOUT_SECONDS;
		return {
			command: env.GATEKEEPER_AGENT_COMMAND,
			timeoutSeconds,
			source: "env",
			description: "using agent from GATEKEEPER_AGENT_COMMAND",
		};
	}

	const configuredAgent = input.discovered?.config.agent;
	if (configuredAgent) {
		return {
			command: configuredAgent.command,
			timeoutSeconds: configuredAgent.timeoutSeconds,
			source: "config",
			description: "using agent from .gatekeeper.yml (agent.command)",
		};
	}

	if (!input.registryPath) {
		return undefined;
	}
	const agentsPath = locateAgentsFile(input.registryPath);
	if (!agentsPath) {
		return undefined;
	}
	let agentsFile: Awaited<ReturnType<typeof loadAgentsFile>>;
	try {
		agentsFile = await loadAgentsFile(agentsPath);
	} catch (error) {
		// Tier 3 is a convenience fallback (see doc comment) -- a damaged agents.yaml must
		// never block a run that's about to fail loud on the caller's missingAgentMessage
		// path anyway, so this still falls through to `undefined` rather than throwing. But
		// silently doing so would make "agents.yaml is broken" indistinguishable from
		// "nothing configured at all" -- name the file and the reason on stderr first.
		if (error instanceof AgentsFileParseError) {
			process.stderr.write(`warning: governance/agents.yaml (${agentsPath}) failed to parse: ${error.message}\n`);
		} else if (error instanceof AgentsFileReadError) {
			process.stderr.write(`warning: governance/agents.yaml (${agentsPath}) could not be read: ${error.reason}\n`);
		} else {
			throw error;
		}
		return undefined;
	}
	const assignment = agentsFile.assignments.find((entry) => entry.role === input.role);
	if (!assignment) {
		return undefined;
	}
	return {
		command: assignment.command_template,
		timeoutSeconds: DEFAULT_AGENT_TIMEOUT_SECONDS,
		source: "agents.yaml",
		description: `using agent from governance/agents.yaml (${input.role}: ${assignment.cli})`,
	};
}
